name = "RegionGrids"
uuid = "ecebd26c-3930-4a82-94f6-9df2a191b288"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "0.0.1"
desc = "Extracting and Subsetting Gridded Data for a given Geographical Region"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GeoRegions = "b001f823-fa75-4bff-bf55-6610c8f3688a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
GeoRegions = "^7"
Reexport = "1"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
