name = "RegionGrids"
uuid = "ecebd26c-3930-4a82-94f6-9df2a191b288"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
