name = "RegionGrids"
uuid = "ecebd26c-3930-4a82-94f6-9df2a191b288"
desc = "Extracting and Subsetting Gridded Data for a given Geographical Region"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "0.1.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GeoRegions = "b001f823-fa75-4bff-bf55-6610c8f3688a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Dates = "1"
GeoRegions = "^8.0.1"
Logging = "1"
julia = "^1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
